### ISSUE TITLE
add new features?

### ISSUE THREAD

**Issue by papo-o** [Cyr-ius/hass-livebox-component#10]
Hello,
would it be possible to add the following functions,
supported by the livebox, please:
list of telephone calls,
reset the call list...

**Comment by JBSoft** [comment]
Hello,

would it be possible to add also :
- wifi status (on/off)
- number of clients connnected on wifi ? (so I can stop wifi automatically when nobody uses it after 10pm for example)

thanks for already great job ! worked smooth on first trial !

**Comment by Cyr-ius** [comment]
> Hello,
> 
> would it be possible to add also :
> 
>     * wifi status (on/off)
> 
>     * number of clients connnected on wifi ? (so I can stop wifi automatically when nobody uses it after 10pm for example)
> 
> 
> thanks for already great job ! worked smooth on first trial !

the switch that turns the wifi on or off represents the wifi status.
You can turn on the wifi from the box, you will see the switch adapts.
I have just added the number of wifi or wired clients on the WanStatus sensor (version 1.5.1)

**Comment by JBSoft** [comment]
So fast! thanks a lot!

**Comment by papo-o** [comment]
it is possible to consult the list of recent calls with
```curl -s -b \""..myCookies.."\" -X POST -H 'Content-Type: application/x-sah-ws-4-call+json' -H \"X-Context: "..myContextID.."\" -d \"{\\\"service\\\":\\\"VoiceService.VoiceApplication\\\",\\\"method\\\":\\\"getCallList\\\",\\\"parameters\\\":{}}\" http://"..LB_address.."/ws```

clear call list with ```curl -m1 -s -b \""..myCookies.."\" -X POST -H 'Content-Type: application/x-sah-ws-4-call+json' -H \"X-Context: "..myContextID.."\" -d \"{\\\"service\\\":\\\"VoiceService.VoiceApplication\\\",\\\"method\\\":\\\"clearCallList\\\",\\\"parameters\\\":{}}\"http://"..LB_address.."/ws ```

reboot livebox with ```curl -m1 -s -b \""..myCookies.."\" -X POST -H 'Content-Type: application/x-sah-ws-4-call+json' -H \"X-Context: "..myContextID.."\" -d \"{\\\"parameters\\\":{}}\" http://"..LB_address.."/sysbus/NMC:reboot```


ring the phone ```curl -m1 -s -b \""..myCookies.."\" -X POST -H 'Content-Type: application/x-sah-ws-4-call+json' -H \"X-Context: "..myContextID.."\" -d \"{\\\"parameters\\\":{}}\" http://"..LB_address.."/sysbus/VoiceService/VoiceApplication:ring```

**Comment by lolo19430** [comment]
> Bonjour,
> serait-il possible d'ajouter les fonctions suivantes,
> supportées par la livebox, s'il vous plaît:
> liste des appels téléphoniques,
> réinitialisation de la liste d'appels ...

tout a fait d'accord +1

**Comment by Cyr-ius** [comment]
Add feature to 1.6.1
- Add binary sensor call missed
- Add service to remove call list
Becarreful , only call missed are display. 
Calls list is not necessary to HA

**Comment by papo-o** [comment]
thanks for that 
remove service call list works fine, binary sensor attributes show the missed call.
but binary sensor is always on even when the missed call list is empty.  it's normal?
(with 1.6.2 version)
![MissedCall](https://user-images.githubusercontent.com/25136535/120094167-21ca8700-c11f-11eb-9899-bc7123c4074a.png)

**Comment by Cyr-ius** [comment]
Fix in 1.6.3

> thanks for that
> remove service call list works fine, binary sensor attributes show the missed call.
> but binary sensor is always on even when the missed call list is empty. it's normal?
> (with 1.6.2 version)
> ![MissedCall](https://user-images.githubusercontent.com/25136535/120094167-21ca8700-c11f-11eb-9899-bc7123c4074a.png)

Fixed in version 1.6.3

**Comment by papo-o** [comment]
work fine with 1.6.3
thanks
