### ISSUE TITLE
aiosysbus==1.1.6 error

### ISSUE THREAD

**Issue by coolkeve** [cyr-ius/hass-livebox-component#104]
Hello, 

After updated the last version of the integration, I have an error. 
Of course after that I tried with the beta version but same issue.... 

Unable to install package aiosysbus==1.1.6: ERROR: Cannot install aiosysbus==1.1.6 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

Setup failed for custom integration 'livebox': Requirements for livebox not found: ['aiosysbus==1.1.6'].

HA CORE 2023.12.1
HA OS 11.2

Do I need to update HA CORE ? 

Thanks for you help.

**Comment by cyr-ius** [comment]
For me, there is no reason for you to update HA CORE. The aiosysbus component requires very few dependencies, it needs python 3.11 and aiohttp and yarl

We may have a conflict with Yarl who also exists in HA.
I'm looking at this...

**Comment by cyr-ius** [comment]
Indeed you have to install the HA CORE version because the yarl version is too old

Latest version  , yarl 1.9.4
https://github.com/home-assistant/core/blob/master/requirements.txt

2023.12.1 , yarl 1.9.2
https://github.com/home-assistant/core/blob/2023.12.1/requirements.txt

aiosysbus , yarl 1.9.3 or above

**Comment by cyr-ius** [comment]
Are you having a problem installing the latest version of HA ? Because I could accept the yarl version 1.9.2 but if we can avoid that would be much better ?

**Comment by coolkeve** [comment]
Thanks for the quick reply ! 

I don't mind updating HA but i'll do that when I'll have time to do it properly (backup / snapshot etc ) just in case :) 
I'll keep you posted.

**Comment by coolkeve** [comment]
It's working fine but now Melcloud integration is not showing up climate entities with HA 2024.1.6... I hate updates sometimes ! 

Thanks for you help @cyr-ius
