### ISSUE TITLE
Fiber RX/TX wrong unit?

### ISSUE THREAD

**Issue by bvalat** [cyr-ius/hass-livebox-component#131]
Hi, on 2.3.5-beta1  fiber Rx/Tx is Mbits/s but (at least for lb6) it is not a speed but a total size of traffic.
Wifi Rx/Tx is ok 

![2024-08-24 (4)](https://github.com/user-attachments/assets/c1952475-f573-49a4-8736-27017817f0f6)

See Livebox Monitor 1.4 : 

![2024-08-24 (3)](https://github.com/user-attachments/assets/dc56f98d-2146-419f-a43c-69677fed1e47)

**Comment by miljbee** [comment]
Hello,
Same problem with LB4. The fiber RX/TX Sensors unit should be MBytes with a state_class Total_Increasing.

**Comment by jms667** [comment]
Hello, any news about this ? Still same issue in 2.4.1 or 2.4.3. sensor fiber rx/tx are a total size of traffic cycling over and over when 4 GB are reached.
