### ISSUE TITLE
Config entry 'Livebox' from integration livebox has an invalid unique_id 'False' of type bool when a string is expected

### ISSUE THREAD

**Issue by amber7212** [cyr-ius/hass-livebox-component#140]
Hi,

An error is reported systematically at HA start:
"Config entry 'Livebox' from integration livebox has an invalid unique_id 'False', please create a bug report at https://github.com/cyr-ius/hass-livebox-component/issues"

Removing the integration leaves some error : "livebox integration not found"

Please update ASAP as it is generating systematic errors at startup/ after uninstall

**Comment by cyr-ius** [comment]
Fix release 6.3.7, please feedback..

**Comment by slamp** [comment]
The issue still exist on version 2.3.9
https://github.com/cyr-ius/hass-livebox-component/releases/tag/2.3.9
