### ISSUE TITLE
Disable wifi connected devices

### ISSUE THREAD

**Issue by scheffer78450** [cyr-ius/hass-livebox-component#146]
Hi,

Thanks a lot for your component running fine with latest beta for my Livebox 7.
All info datas about the Livebox are great but I would like to avoid each connected devices to be listed into hass, is there a config setting to disable it like the option to add lan devices ?

**Comment by cyr-ius** [comment]
I can add an option to disable Wi-Fi items. you will have more device trackers

**Comment by cyr-ius** [comment]
Please try 6.3.8-beta1 and feedback

**Comment by nscheffer** [comment]
Hi,
Happy to see your comment !
Immediately download and install the 6.3.8-beta1 but failed to add the Livebox.
Re-install 6.3.7 and add Livebox with success
Try to upgrade to 6.3.8-beta1 but failed : 
![image](https://github.com/user-attachments/assets/89dcbda8-bcbd-4244-8de0-5a7c87682917)

**Comment by nscheffer** [comment]
Let me know if you need more info to troubleshoot the problem.

**Comment by cyr-ius** [comment]
Please upload debog log or home assistant log

**Comment by nscheffer** [comment]
I remove completely Orange Livebox Router from HACS
Check configuration.yaml has no entry, done
Re-install latest beta and go the error message when trying to add the Orange Livebox Router Integration : "Invalid handler specified"

Attached screenshot and home-assistant.log
![Capture d’écran 2024-12-05 à 08 52 23](https://github.com/user-attachments/assets/03f31099-573f-4ddb-a3bc-bf6f43e82ec3)
[home-assistant.log](https://github.com/user-attachments/files/18019388/home-assistant.log)

**Comment by nscheffer** [comment]
6.3.7 is working fine, no problem.
From 6.3.7 trying to upgrade to 6.3.8-beta1 same problem

**Comment by cyr-ius** [comment]
Thk , issue is patched. Please try 6.3.8-beta2

**Comment by nscheffer** [comment]
Working without Wifi devices, you rock !!

**Comment by nscheffer** [comment]
The option does not track anymore Wifi devices but how to remove all existing know devices from the Livebox into HA ?
I would like to use all KPI from the Livebox (TX, RX speed and db, etc....) but not the devices known from the Livebox, in my case you can see I have 71 devices and my HA has nearly double devices because of this new addition.
Let me know how to do it or if a patch need to be applied ?

**Comment by nscheffer** [comment]
Maybe corrupted data from previous build and install, I manually removed all 71 devices and now it's perfect just got Livebox Sensors with traffic metrics and that's it !!!!
You can close this issue.
Thanks for your reactivity.
