### ISSUE TITLE
Config entry 'Livebox' from integration livebox has an invalid unique_id 'False' of type bool when a string is expected

### ISSUE THREAD

**Issue by sleveille4** [cyr-ius/hass-livebox-component#147]
since update to  core 2024.11.1 this error is displayed in the log:

`2024-11-10 11:50:37.352 ERROR (MainThread) [homeassistant.config_entries] Config entry 'Livebox' from integration livebox has an invalid unique_id 'False' of type bool when a string is expected, please create a bug report at https://github.com/cyr-ius/hass-livebox-component/issues`

**Comment by cyr-ius** [comment]
Fix release 6.3.7, please feedback..
