### ISSUE TITLE
Download & Upload rates remains at 0 on Livebox 5

### ISSUE THREAD

**Issue by acommuni** [cyr-ius/hass-livebox-component#148]
Hello,

Download & Upload rates remains at 0

![image](https://github.com/user-attachments/assets/cd442e96-afd0-47a6-8b3a-0d2389eb86e8)

But they are not in fact at 0

![image](https://github.com/user-attachments/assets/29014e4a-df3f-49b7-9709-59c9b7959f2c)

I could help to find th right request / attribute.

**Comment by 0berkampf** [comment]
Same issue for me here with a livebox 5 as well.

**Comment by Gumpy-Q** [comment]
As a janky fix : 
Get the Beta version on HACS to add two new sensors (Tx and Rx), while they are shown as MBit/s in reality they are a cycling counter of your down and up data usage from 0 to ~40GB updated every minutes.

You can then add the two following sensors to your config.yaml

`
  - platform: derivative
    source: sensor.livebox_fibre_fiber_rx
    name: débit descendant livebox
    round: 2
    unit_time: s
    unit: MB/s
    time_window: "00:02:00"

  - platform: derivative
    source: sensor.livebox_fibre_fiber_tx
    name: débit montant livebox
    round: 2
    unit_time: s
    unit: MB/s
    time_window: "00:02:00"`


I'm not 100% certain if they are MB or MiB but it pretty close to what you want.

Be aware that when the counter cycle to 0, you will get a negative high value.

From my understanding, LiveboxMonitor do the same but with a 3s derivative and have a mechanisme to avoid the incoherent value when cycling to 0.

**Comment by acommuni** [comment]
Which Beta do I need to get ? The 2.3.5-beta1 was published in May, is this one ok ?

**Comment by Gumpy-Q** [comment]
> Which Beta do I need to get ? The 2.3.5-beta1 was published in May, is this one ok ?

This is the beta i use.
To get a better refresh rate, I've fiddle within the custom component of the integration. The coordinator.py have a line SCAN_INTERVAL i've reduced to seconds=20.
As i've reduce the scan interval I've also make the derivative on 20s.

**Comment by acommuni** [comment]
Thank you, it seems to be Ok now with the last beta version
