### ISSUE TITLE
device_tracker configuration for livebox component

### ISSUE THREAD

**Issue by Shkrum31** [Cyr-ius/hass-livebox-component#15]
Hi,

I would like to use the consider_home parameter in order to prevent false "not_home" situation when Apple iOS devices go into sleep mode.

The following code inserted in the configuration.yaml was unsuccessful:

```
device_tracker:
  - platform: livebox
    consider_home: 180
```

I guess this is because the livebox component is not listed as an official presence-detection integration.

Do you have any suggestion ?

Thanks

**Comment by Cyr-ius** [comment]
> Hi,
> 
> I would like to use the consider_home parameter in order to prevent false "not_home" situation when Apple iOS devices go into sleep mode.
> 
> The following code inserted in the configuration.yaml was unsuccessful:
> 
> ```
> device_tracker:
>   - platform: livebox
>     consider_home: 180
> ```
> 
> I guess this is because the livebox component is not listed as an official presence-detection integration.
> 
> Do you have any suggestion ?
> 
> Thanks

Add feature in latest version
