### ISSUE TITLE
Update to 2.3.7 create a second livebox

### ISSUE THREAD

**Issue by myB0B** [cyr-ius/hass-livebox-component#153]
just update the module to 2.3.7 in my HA 2024.11.1.
the module create a new livebox instead of update the existing one
![Capture d'écran 2024-12-04 120434](https://github.com/user-attachments/assets/401ab969-7e80-45fd-b1de-5b796df1f28d)

**Comment by cyr-ius** [comment]
Please ,  upload diagnostic ande debig log

**Comment by myB0B** [comment]
Okay, I hadn't read the note.
