### ISSUE TITLE
Feature Request - Add IP Address and Connection point to Device or device_trackers

### ISSUE THREAD

**Issue by StephaneStolz** [cyr-ius/hass-livebox-component#155]
Bonjour,

Merci pour cette intégration qui est très utile et bien conçue.

Je souhaiterai pouvoir consulter l'adresse IP des éléments connectés qui ont crée un device_tracker.
Pour le moment on a accès à la MAC address, mais pas l'IP address.

Aussi, si possible, connaitre le point de connection. (BSSID)
J'ai deux repeteurs WiFi (Bureau et Chambre) et si je savais lequel est utilisé, ça me permettrai de localiser plus précisément où se trouve l'équipement.
Par exemple, si l'iPhone de mon fils est connecté au Repeteur "Bureau", je pourrait le localiser avec plus de précision.

Merci

**Comment by cyr-ius** [comment]
Peux tu me déposer le fichier de diagnostic afin que je puisse connaitre les infos côté Box

**Comment by StephaneStolz** [comment]
[config_entry-livebox-01JF2ND93P966NBJVR023BJ9W3.json](https://github.com/user-attachments/files/18136892/config_entry-livebox-01JF2ND93P966NBJVR023BJ9W3.json)
Le voilà
C'est une Livebox 7

**Comment by cyr-ius** [comment]
Si tu regardes ton diag , tu verras tes équipements apparaitres à la ligne 163 ,  je peux ajouter l'IP Address mais je vois pas le BSSID du point de connection

**Comment by cyr-ius** [comment]
J'ai épluché tout le fichier , les équipements n'indiquent pas le SSID qu'ils ont attrapés et l'adresse ip est déjà remonté sur le device tracker dans la section attributs. Je te laisse regardé le fichier plus en amont.

**Comment by StephaneStolz** [comment]
Effectivement, je ne trouve pas non plus.
Au moins, l'adresse IP est déjà présente... donc on clos cette requête

Merci d'avoir regardé.
