### ISSUE TITLE
Some questions about hass-livebox-component

### ISSUE THREAD

**Issue by monpelaud** [cyr-ius/hass-livebox-component#157]
Hi,
I'm using hass-livebox-component and have a few questions.

I did a basic install of hass-livebox-component. No problem, the Livebox component entities have been created on HA.
Orange-Livebox integration also created two entities for my PC:
- device_tracker.mypc
- switch.desktop_mypc_wan_access

My questions are:
- Why did Orange Livebox integration create these two entities for my PC?
- Why not for other wifi devices connected to the livebox?
- I want to track my smartphone, at-home and not-at-home. How can I create a HA device_tracker entity for my smartphone like hass-livebox-component did automatically for my PC?

Thanks for your help.

**Comment by cyr-ius** [comment]
Why did Orange Livebox integration create these two entities for my PC?
The first object allows you to track your device and the second authorizes or not the equipment to access the Internet

Why not for other wifi devices connected to the livebox?
Now the livebox goes back to all WiFi or Wired equipment, you should see your phone. All devices you see in the box must be seen in HA

If you don't see your phone, check to see if you see it in your box and if so. Give me your diagnostic file

**Comment by monpelaud** [comment]
Hi,
Sorry, I'm an idiot!
Behind my livebox I have an ASUS router in access point mode! My wifi devices are connected to my ASUS router not to my Livebox...
Thanks for your help.
