### ISSUE TITLE
NO access to LiveBox in Spain. Same error as above. 

### ISSUE THREAD

**Issue by soshedro** [Cyr-ius/hass-livebox-component#19]
Hello,

I have the same problem here on Spain Orange Livebox router, "Unknown error", inserting user/password info.

This could be by the software version.

Do you know which can be the trouble?

John

**Comment by soshedro** [comment]
http://192.168.1.1/ws

With this info:   "Not Found"

Json not working?

**Comment by chpego** [comment]
@soshedro it's the same with http://livebox.home/ws ?

**Comment by Cyr-ius** [comment]
Please enable debug mode in Home assistant
homeassistant.custom_components.livebox: debug in log section
And paste result

**Comment by ch0wch0w** [comment]
I getting some problems here too. I need to install another but don't know how.

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 541, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/livebox/__init__.py", line 14, in <module>
    from .bridge import BridgeData
  File "/config/custom_components/livebox/bridge.py", line 4, in <module>
    from aiosysbus import AIOSysbus
ModuleNotFoundError: No module named 'aiosysbus'`

**Comment by jackercito** [comment]
Same problem here

Log error:

ERROR (MainThread) [custom_components.livebox.bridge] Error Not open (Open session failed (APIResponse: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))).

**Comment by mfigueroa7** [comment]
Same here.

http://192.168.1.1/ws

With this info: "Not Found"

**Comment by alexisteleco** [comment]
> @soshedro it's the same with http://livebox.home/ws ?

Yes, same here:
![image](https://user-images.githubusercontent.com/17027081/111080303-2313ec80-84fe-11eb-903f-860e66948736.png)

**Comment by soshedro** [comment]
Yes, same error as other users said. "404"

**Comment by comedido** [comment]
same error here @spain

**Comment by Cyr-ius** [comment]
Do you know the url that we should call because in France, we have a / WS

**Comment by comedido** [comment]
I don't know, is there a way to scrape it? I know the firmware might have been altered here for security purposes.

**Comment by Cyr-ius** [comment]
It would be necessary to activate the Developer mode on Chrome and browse the Livebox to see which calls are

> I don't know, is there a way to scrape it? I know the firmware might have been altered here for security purposes.

**Comment by comedido** [comment]
I had a look at the Network requests in chrome while navigating my router configuration screens. It seems all requests go directly to http://192.168.1.1:80 so no path with /ws

All web resources are get like:
- http://192.168.1.1/js
- http://192.168.1.1/css
- http://192.168.1.1/images
- http://192.168.1.1/cgi

Is there anything else that I can do or look for?

**Comment by Cyr-ius** [comment]
The /ws interface allows to control the exposed webservices unfortunately with these elements I can't do anything.
It is necessary to identify the calls to the API
