### ISSUE TITLE
No data on Speed informations - Livebox v4

### ISSUE THREAD

**Issue by scoubidoo** [Cyr-ius/hass-livebox-component#2]
hello,
i used a history-graph to show the speed on my livebox but it return to me  no data.
`- type: history-graph
        entities:
          - entity: sensor.orange_livebox_download_speed
          - entity: sensor.orange_livebox_upload_speed
        hours_to_show: 24
        refresh_interval: 0
        title: Livebox`

**Comment by Cyr-ius** [comment]
I do not have any problems.
try to remove and reinstall the component
What do you see directly in developer mode on the sensor.orange_livebox_download_speed

I'm developing on a v3 livebox

![image](https://user-images.githubusercontent.com/1258123/71778864-8083e380-2fb3-11ea-85be-8ff786596df4.png)

**Comment by simulot** [comment]
I have same issue. I'm using a LB4.

**Comment by ivico94** [comment]
Hi there!

Same issue as simulot on LB4 :-(

I customised livebox dashboard (not the default one). Can this be a source of problem with this integration?

Anyway, maybe you can consider changing your livebox @Cyr-ius ? LB4 is more energy efficient, has better wifi, is smaller and has dedicated wifi channel for TV.

Moreover, it cost only 10€ to change it in any Orange shop.

Hope this help.

Thanks

**Comment by Cyr-ius** [comment]
Can you activate beta mode and select version 1.3.7-beta2 in HACS
And give me feedback, I rewrote the aiosysbus API to be compatible with version 4
(completely blind because I don't have the box)

**Comment by simulot** [comment]
I have have updated to 1.3.7-beta3.
Unfortunately, i can't see any change.

**Comment by mehdi-baylibre** [comment]
Hi @Cyr-ius , I'm also on a Livebox 4 and have no data for upload and download speed.
I can help you debug if you want...

**Comment by Cyr-ius** [comment]
we have to take traces with wirehark
Launch wirehsark to listen on the network card, then surf with a browser on the pages of the livebox4
stop the trace and drop the pcap file
This will analyze the calls and know the right orders to place and retrieve

**Comment by mehdi-baylibre** [comment]
Ok, I'll try to do this Saturday...

**Comment by guedjm** [comment]
Hi,
I have th same issue on a Livebox v3. How can i help ?

![image](https://user-images.githubusercontent.com/5198056/73100449-db8f6300-3eed-11ea-815c-985aa9da4f75.png)
![image](https://user-images.githubusercontent.com/5198056/73100530-011c6c80-3eee-11ea-85b2-031d04635e31.png)

Thank you

**Comment by ivico94** [comment]
Hi @Cyr-ius 

I have a pcap file for you but i'd prefere not to attach it here. Can I send it to you in private please? How?

**Comment by Cyr-ius** [comment]
Goood
you send : git-livebox4@ipocus.net

**Comment by Cyr-ius** [comment]
> Hi @Cyr-ius
> 
> I have a pcap file for you but i'd prefere not to attach it here. Can I send it to you in private please? How?

Goood
you send : git-livebox4@ipocus.net

**Comment by ivico94** [comment]
Done!

**Comment by kerozen54** [comment]
Hi all.
this componenet is working well for me with a livebox 4 (latest firmware, updated few days ago).
![image](https://user-images.githubusercontent.com/25516195/74519747-98d21100-4f16-11ea-8aae-d826ea72abbe.png)

But is it hard to get other values from the livebox ?
For exemple :
FECErrors
ATUCFECErrors
CRCErrors
HECErrors
ATUCHECErrors
ATUCCRCErrors
and maybe other ?

**Comment by Cyr-ius** [comment]
After an exchange with ivico94, and by analyzing the traces of a Livebox 4 and a 3, I come to the conclusion that the speed is not indicated if you are in FTTH

**Comment by hot22shot** [comment]
I have the same issue with a LB5 (also with FTTH).

**Comment by Cyr-ius** [comment]
> I have the same issue with a LB5 (also with FTTH).
> That being said the LB5 speed are available through UPNP.

Do you have the detail?

**Comment by simulot** [comment]
As far as I know, the API is no more accessible with LB5, or the API has changed.
Anyway, the LB5 is providing some data through UOnP integration

Here are entities provided: 
![image](https://user-images.githubusercontent.com/5980377/120096966-71fd1580-c12e-11eb-991f-4041e6c84a3b.png)



![image](https://user-images.githubusercontent.com/5980377/120096851-fc914500-c12d-11eb-982b-70bebf0750c5.png)
