### ISSUE TITLE
Strange to have 5 devices and 4 entities

### ISSUE THREAD

**Issue by oncleben31** [Cyr-ius/hass-livebox-component#25]
Thank you for your custom component. From my point of view it is strange to see 5 devices in the configuration tile.

<img width="261" alt="Capture d’écran 2020-11-04 à 17 16 12" src="https://user-images.githubusercontent.com/93244/98136652-75466080-1ec1-11eb-9f19-d6536ece85c9.png">

Perhaps you should review how the entities are implemented. I expect to have 1 device (one by livebox) and X entities (one by component you implement)

**Comment by Cyr-ius** [comment]
Fix with latest version

**Comment by oncleben31** [comment]
Thank you for the fix.
For information making the update thru HACS add the new device with all the entities but the old devices are still there.
For a future update you should look at the [migration feature](https://developers.home-assistant.io/docs/config_entries_config_flow_handler/#config-entry-migration) to avoid this type of side effect.
