### ISSUE TITLE
Merci

### ISSUE THREAD

**Issue by edelans** [Cyr-ius/hass-livebox-component#28]
Bonjour, 

Je viens de découvrir ce component dans HACS et c'est ce qu'il manquait pour rendre ma détéction de présence beaucoup plus fiable. Donc je voulais simplement vous dire merci =)

**Comment by Cyr-ius** [comment]
Toujours plaisant de dire Merci.

Merci.

> Bonjour,
> 
> Je viens de découvrir ce component dans HACS et c'est ce qu'il manquait pour rendre ma détéction de présence beaucoup plus fiable. Donc je voulais simplement vous dire merci =)
