### ISSUE TITLE
LiveBox v4 - Configuration failed

### ISSUE THREAD

**Issue by pinkfloydFR** [Cyr-ius/hass-livebox-component#36]
Hi, 

When i enter all information of my livebox 👍 

ip : 192.168.0.254
login : admin
mdp ; xxxxxxxx!
port : 80

i got the message 'abandonné' ie 'canceled' in english.

I am sure of all data i enter.

thanks.

**Comment by plouf34** [comment]
Same for me, the integration seems to be break.

**Comment by Cyr-ius** [comment]
are you sure of your ip address?
