### ISSUE TITLE
Livebox 4 - Sensors Upload and Download unavailable

### ISSUE THREAD

**Issue by xekil** [Cyr-ius/hass-livebox-component#37]
Hello,

Since I switched to Fiber and the livebox 4 was updated to version 4.15.10, the Upload and Download sensors are unavailable

Any ideas?

Thank you

Ha core - 2021.9.3
hass-livebox-component -  1.6.3

**Comment by Cyr-ius** [comment]
Fix 1.6.8

**Comment by xekil** [comment]
Thanks ;)

**Comment by xekil** [comment]
update 1.68 made but the problem is still there :(
