### ISSUE TITLE
LB4  HTTP Request Error HttpRequest (APIResponse: 504)

### ISSUE THREAD

**Issue by tomdudu38** [Cyr-ius/hass-livebox-component#42]
hi
i have a Livebox4
this hassio integration spam this in log:

`Logger: custom_components.livebox.bridge
Source: custom_components/livebox/bridge.py:69
Integration: Orange Livebox (documentation, issues)
First occurred: 6:45:21 (2 occurrences)
Last logged: 6:45:22

HTTP Request Error HttpRequest (APIResponse: 504).`

ERROR (MainThread) [custom_components.livebox.bridge] HTTP Request Error HttpRequest (APIResponse: 504).
why?
thanks

**Comment by ullrik** [comment]
Après quelques recherche, le problème vient d'un changement d'appel de WS avec la livebox V4. 
A savoir que cette intégration Home assistant se base sur l'API AIOSysbus (https://github.com/Cyr-ius/aiosysbus) qui malheureusement ne gère pas ce changement. 
J'ai vu qu'un autre dev avait créé une API qui gère la v3, v4 et v5 ici : https://github.com/rene-d/sysbus

Pour le moment je vais tenter de faire évoluer lAIOSysbus pour gérer la v4 en espérant qu'il accepte ma modification.

**Comment by tomdudu38** [comment]
Je suis passé sur nmap.
Car debugger chaque intégration cela prend trop de temps.alors qu' il y a d autre alternative plus ou moins efficace.comme peu etre utiliser directement l api

**Comment by xekil** [comment]
same problem

**Comment by Toukite** [comment]
Même problème de mon côté !

**Comment by Cyr-ius** [comment]
Please enable debug mode
logger:
  logs:
    custom_components.livebox: debug
    aiosysbus: debug
