### ISSUE TITLE
Feature Request : LB5 Support

### ISSUE THREAD

**Issue by hot22shot** [cyr-ius/hass-livebox-component#43]
Hello,

I understant that download/upload speeds were not available through the sysbus API anymore on LB5, but you can collect them with a webservices (see https://github.com/rene-d/sysbus/issues/28).

Do you plan to add support for LB5 ?

**Comment by ludoComp9** [comment]
Same question for LB6

**Comment by Aohzan** [comment]
You can get speeds from [upnp integration](https://www.home-assistant.io/integrations/upnp/) if you want

**Comment by WarC0zes** [comment]
@Aohzan 
Bonjour, j'ai installer l'intégration upnp pour la livebox 6 et le upnp est bien activer sur la box. Mais les capteur reste a 0 kb/s malgré que je donwload. As tu configurer quelque chose pour que ca fonctionne chez toi ?

**Comment by Aohzan** [comment]
J'avais une LB5, mais Je ne me rappelle pas avoir fait quoi de ce soit. Je n'utilise plus l'intégration car je suis passé sous OpenWRT du coup je vais pas pouvoir plus aider désolé
