### ISSUE TITLE
Setup failed for button: Integration not found.

### ISSUE THREAD

**Issue by WarC0zes** [Cyr-ius/hass-livebox-component#44]
Since update 1.6.9, I have an error message. If I back to version 1.6.8, I not have an error.

**system info :**
Livebox v3
core-2021.11.3
supervisor-2021.10.8
Home Assistant OS 6.6
rpi 3b

```
Logger: homeassistant.setup
Source: setup.py:178
First occurred: 16:56:23 (1 occurrences)
Last logged: 16:56:23

Setup failed for button: Integration not found.
```
![notify](https://user-images.githubusercontent.com/91471397/141497353-4846edb5-9795-4051-8331-902fa1b04a12.jpg)

**Comment by xekil** [comment]
same error

**Comment by WarC0zes** [comment]
After the core 2021.12.0 update, no error ;)
