### ISSUE TITLE
Livebox V4 PRO integration doesnt work

### ISSUE THREAD

**Issue by Electronlibre2012** [Cyr-ius/hass-livebox-component#5]
Hello,

i have been so happy to see an integration for the Livebox lol but sadly...it doent work on my Livebox V4 PRO : when i 've been prompt to enter information like IP, Port, username and password, i type the password and i have a "Unknown linking error occurred".

Any idea?

Thanks

Olivier

**Comment by Cyr-ius** [comment]
please check again ?

**Comment by Electronlibre2012** [comment]
sorry,  it doesnt work..."unknow error" no change
