### ISSUE TITLE
Integration fail

### ISSUE THREAD

**Issue by JmRy** [Cyr-ius/hass-livebox-component#50]
Hello,

I have an error while integrating you component.

https://my.home-assistant.io/redirect/config_flow_start/?domain=livebox displays the message `Voulez-vous configurer livebox` _(Do you want configure livebox)_ but after `Le flux de configuration n'a pas pu être chargé` _(The configuration flow could not be loaded)_

My config

- HAS 2021.11.5 in VirtualBox VM
- OS 6.6
- supervisor-2021.10.8
- your component 1.6.9
- Livebox 4

Note : 

1. The livebox is connected behind OpenMPTCProuter. So it has a different IP from the HAS network  (HAS = 192.168.10.100 LB = 192.168.30.1). But I can access it from any computer on my network 192.168.10.x.

2. I also have a very closed firewall, maybe open a special port?

Thank you for your help

_PS: I'm a beginner and test HAS_  ;-)

**Comment by fslef** [comment]
I'm running into the same issue.

**Comment by manuelchantada** [comment]
same issue. How can I get started debugging it?

**Comment by Cyr-ius** [comment]
Please enable debug in configuration.yaml

logger:
  logs:
    custom_components.livebox: debug

**Comment by manuelchantada** [comment]
Hi, thank you for your response.
In my case it was only that I was missing installing hacs.
Still I cannot use this integration it gives an error when connecting: "Unknown error occurred"
