### ISSUE TITLE
integration de 2 boutons

### ISSUE THREAD

**Issue by romain1206** [Cyr-ius/hass-livebox-component#51]
reboot de la livebox

http://IPBOX/sysbus/NMC:reboot

faire sonner telephone fixe

http://IPBOX/sysbus/VoiceService/VoiceApplication:ring

merci

**Comment by chpego** [comment]
Pour la partie **"faire sonner telephone fixe"** ça ne semble pas être dans le script python [ici](https://github.com/Cyr-ius/aiosysbus/blob/bfd7f7a0926010d76a000cfdb2332f471481a495/aiosysbus/api/call.py)

**Comment by romain1206** [comment]
sur ce script il le font

https://github.com/papo-o/domoticz_scripts/blob/d7b44be49cbfa9756275cfc5a4b9721885fe5805/dzVents/scripts/livebox.lua

ligne 526

je l'ai sur mon ancienne installation domoticz (et ca fonctionne encore) je l'utilise avec HA via l'api domoticz

**Comment by chpego** [comment]
> sur ce script il le font
> 
> https://github.com/papo-o/domoticz_scripts/blob/d7b44be49cbfa9756275cfc5a4b9721885fe5805/dzVents/scripts/livebox.lua
> 
> ligne 526
> 
> je l'ai sur mon ancienne installation domoticz (et ca fonctionne encore) je l'utilise avec HA via l'api domoticz
> 
> si il y a besoin de faire des tests je suis disponible (livebox v4)

j'ai créé une issue et associé une PR, on verra bien ce qu'en pense @Cyr-ius  ;)

**Comment by papo-o** [comment]
sympa de voir ça par la :)

**Comment by Cyr-ius** [comment]
Ajout réaliser
