### ISSUE TITLE
Automatisation wifi

### ISSUE THREAD

**Issue by pebteam** [Cyr-ius/hass-livebox-component#52]
Bonjour,
Je suis un nouvel utilisateur de home assistant.
J'ai installé votre composant livebox.
Pouvez-vous m'indiquer quelle procédure je dois suivre pour programmer depuis home assistant une extinction du wifi de la livebox à une heure précise ?
Vous en remerciant par avance.
Salutations distinguées.

**Comment by romain1206** [comment]
bonjour,

c'est pas vraiment le lieu pour répondre, mais bon

dans configuration / integration / orange livebox / tu clique sur apapreils / le nom de la livebox

tu devrais voir apparaitre le bouton "switch wifi" , call missed, wan status

a droite tu clique sur "automatisations" et tu selectionne " Quand quelque chose est déclenché … "éteindre wifi"
et tu suis les instructions
