### ISSUE TITLE
HTTP Request Error HttpRequest.

### ISSUE THREAD

**Issue by WarC0zes** [Cyr-ius/hass-livebox-component#57]
Bonjour, 
depuis la maj 1.7.3 j'ai ce message d'erreur qui est apparu deux fois sans trop d'infos. J'ai une livebox v3 et tout a jour sur HA.

```
Logger: custom_components.livebox.bridge
Source: custom_components/livebox/bridge.py:69
Integration: Orange Livebox ([documentation](https://github.com/cyr-ius/hass-livebox-component), [issues](https://github.com/cyr-ius/hass-livebox-component/issues))
First occurred: 09:06:37 (1 occurrences)
Last logged: 09:06:37

HTTP Request Error HttpRequest.

2022-02-06 09:06:37 ERROR (MainThread) [custom_components.livebox.bridge] HTTP Request Error HttpRequest.
```

**Comment by Cyr-ius** [comment]
L'erreur survient quand la livebox ne veut pas répondre à la requête

**Comment by WarC0zes** [comment]
Donc c'est une erreur que je peu ignoré? 
Pour tout te dire j'ai une connection adsl pas stable, avec des gros ping des fois.
Ca pourrais venir de ca?

**Comment by WarC0zes** [comment]
Je viens de mettre a jour le core 2022.2.3 et l'erreur ne c'est pas reproduit. Je pense que ça venait du core et pas de votre intégration. Je cloture , si problème reviens je réouvrirai.
