### ISSUE TITLE
Feature request: Activer/Désactiver le wifi invité

### ISSUE THREAD

**Issue by Gus1994** [Cyr-ius/hass-livebox-component#58]
Bonjour,
Tout d'abord, bravo pour cette intégration très pertinente et utile !
Est il possible d'embarquer à terme la fonctionnalité, activation/désactivation de la wifi invité?
Cette fonctionnalité est déjà dispo sur jeedom donc j'imagine qu'il existe des APIs pour le faire?
https://jmvedrine.github.io/plugin-livebox/fr_FR/
Très utile pour créer une automatisation ou l'on viendrait activer la wifi invité et projeter sur la télévision un QR code pour s'y conencter automatiquement !
![image](https://user-images.githubusercontent.com/4313558/153003005-3d7a17c6-8335-43b8-bd1d-39a3b6445c39.png)
Merci encore pour votre travail :)
Bonne journée,

**Comment by Cyr-ius** [comment]
Up to 1.8.5

**Comment by Gus1994** [comment]
Merci à vous pour cette nouvelle fonctionnalité très utile ! Bonne continuation :)
