### ISSUE TITLE
Livebox wifi 6

### ISSUE THREAD

**Issue by scrakcho** [Cyr-ius/hass-livebox-component#59]
This can work over this new device? Im trying but ...
Or maybe other way to get router info?

**Comment by Cyr-ius** [comment]
Try it

**Comment by WarC0zes** [comment]
Bonjour,
je viens de passer sur une livebox 6 et votre intégration fonctionne avec. Il y a juste les sensors de vitesses qui sont indisponible, mais c'est normal ca n'y est plus dans le menu de la box. 
Tous le restes est opérationnelles, les devices trackers, call missed, button reboot et switch du wifi.

Encore merci pour c'est intégration.
