### ISSUE TITLE
Orange FunBox 3.0 from Poland only wan_status binary sensor work

### ISSUE THREAD

**Issue by L3H0** [Cyr-ius/hass-livebox-component#6]
Hello,

I`m from Poland and i have in my house FTTH on FunBox 3.0.
The integration from you works half.
I have only the corect info from:
- binary_sensor.orange_livebox_wan_status

Any others aren`t working.
When i want to switch Wi-Fi on i got:
'AIOSysbus' object has no attribute 'async_set_wifi'

Can i send any logs to you for more support device tracker, device restart, Wi-Fi?

Device info: SagemcomFast5656_OPL
Software: SG30_sip-pl-03.17.08.17 

Regards

**Comment by Cyr-ius** [comment]
Please update version to 1.4.7 and feed back your test ?

**Comment by L3H0** [comment]
@Cyr-ius today i installed 1.4.8 and the Wi-Fi switch works good.
Any info about others issues?

**Comment by kacpersky** [comment]
I have the same issue on Polish Funbox 3.0. I think the problem is that on FTTH there is no information about speed in WEB UI.

**Comment by Cyr-ius** [comment]
Same issue #2
