### ISSUE TITLE
Failed to install using the "Add Integration" button in the README

### ISSUE THREAD

**Issue by aallrd** [Cyr-ius/hass-livebox-component#68]
Hello,

I clicked on clicking on the "Add Integration" button from the README to add this integration to my Home Assistant installation.
On the Home Assistant integrations page that opens, I get the below error:
> Cette intégration ne prend pas en charge la configuration via l'interface utilisateur. Si vous avez suivi ce lien depuis le site web de Home Assistant, assurez-vous que vous exécutez la dernière version de Home Assistant.

I am using:
- Home Assistant 2022.10.3
- Supervisor 2022.10.0
- Operating System 9.2
- Interface utilisateur : 20221010.0 - latest

Is there another way to install this integration?

**Comment by miguelpucela** [comment]
Same here with HASS 2022.12

**Comment by Cyr-ius** [comment]
It is necessary to add the Livebox module via HACS to then make the integration

**Comment by Cyr-ius** [comment]
Close
