### ISSUE TITLE
Livebox 6

### ISSUE THREAD

**Issue by olybop** [Cyr-ius/hass-livebox-component#69]
Livebox 6 is well detected in HA, wifi devices and some sensor (ip/down) as well.
But no local ip and public ip

Thx for your works

**Comment by WarC0zes** [comment]
@olybop
the public ip is in the wan status sensor and in the attribute.
![livebox ip ext](https://user-images.githubusercontent.com/91471397/202836744-ec790c99-044d-4a8a-bfc1-784c4a5a4153.png)
For local ip, use Nmap Tracker.

**Comment by olybop** [comment]
perfect thx :)
