### ISSUE TITLE
Problème avec 2023.2

### ISSUE THREAD

**Issue by epenet** [Cyr-ius/hass-livebox-component#70]
`Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for livebox using this method at custom_components/livebox/__init__.py, line 98: hass.config_entries.async_setup_platforms(config_entry, PLATFORMS)`

Voir https://github.com/hacs/integration/pull/3038

**Comment by Cyr-ius** [comment]
Up to 1.8.3

**Comment by hugoKs3** [comment]
1.8.3 does not seem to work...

`Config flow could not be loaded: {"message":"Invalid handler specified"}`

**Comment by Cyr-ius** [comment]
Up to 1.8.5
