### ISSUE TITLE
Livebox router: no update of sensors?

### ISSUE THREAD

**Issue by bernardtrigaux** [cyr-ius/hass-livebox-component#75]
Home Assistant 2023.4.6
Supervisor 2023.04.0
Operating System 9.5
Frontend 20230411.1 - latest

Just installed the Livebox router (v1.8.5).
Successfully integrated in HA with my livebox 4

The “sole” issue is that download/upload speed sensors never change
![image](https://user-images.githubusercontent.com/105116907/234229765-fa0c7f1f-ab8a-4dca-8ab1-5d8a32924009.png)

Any idea ?

**Comment by WarC0zes** [comment]
Bonjour,
se sont pas des capteurs de débits qui vont ce modifier suivant votre utilisation de la bande passante.
Se sont juste des capteur d'information des débits max en download et upload de votre connection.

Si vous voulez voir les débit en temps réelle, faut installer l'intégration UPNP.

**Comment by bernardtrigaux** [comment]
Hello, ok thanks for this quite useful clarification.
