### ISSUE TITLE
Device tracker

### ISSUE THREAD

**Issue by LGO44** [cyr-ius/hass-livebox-component#82]
Thanks for the integration,  I propose some enhancement
I use device trackers to monitor the different equipments connected to my livebox. 
Other integrations also provide device trackers. 
In order to filter the equipment linked to the livebox I propose to add an attribute 
"**Scanner =LiveboxDeviceScanner**".
I also modified the **device_tracker.py** file in order to make other informations available to improve devices monitoring.

My device_tracker.py is joined as .zip

An exemple of the displayed data
![image](https://github.com/cyr-ius/hass-livebox-component/assets/95585425/247fc79f-a22a-4a20-8e14-cdf30a1ed4d5)

_
[device_tracker.zip](https://github.com/cyr-ius/hass-livebox-component/files/13062760/device_tracker.zip)

**Comment by LGO44** [comment]
I propose the PR  "Update device_tracker.py #84"

**Comment by cyr-ius** [comment]
I just suggested some improvements. Thanks for looking at the PR.

**Comment by cyr-ius** [comment]
Look at 2.1.2-beta version
