### ISSUE TITLE
Remote access

### ISSUE THREAD

**Issue by LGO44** [cyr-ius/hass-livebox-component#83]
It should be nice to be able to access remotely to a livebox

address   https:// my.ddns.address;network
user   user
password

port: 12000 for example

**Comment by cyr-ius** [comment]
> It should be nice to be able to access remotely to a livebox
> 
> address https:// my.ddns.address;network user user password
> 
> port: 12000 for example

Version 2.0.0-beta offers this functionality when adding a livebox
