### ISSUE TITLE
livebox 6+

### ISSUE THREAD

**Issue by dusnake** [cyr-ius/hass-livebox-component#86]
Hello, I am trying to associate my livebox6+ with a home assistant, but it keeps failing:

Unknown error occurred

 File "/config/custom_components/livebox/config_flow.py", line 71, in async_step_user
    await bridge.async_connect(**user_input)
  File "/config/custom_components/livebox/bridge.py", line 42, in async_connect
    await self.hass.async_add_executor_job(self.api.connect)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)

**Comment by cyr-ius** [comment]
> Hello, I am trying to associate my livebox6+ with a home assistant, but it keeps failing:
> 
> Unknown error occurred
> 
> File "/config/custom_components/livebox/config_flow.py", line 71, in async_step_user await bridge.async_connect(**user_input) File "/config/custom_components/livebox/bridge.py", line 42, in async_connect await self.hass.async_add_executor_job(self.api.connect) File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs)

Please download 2.1.6-beta and retry

**Comment by dusnake** [comment]
I try a few times, always this error:

Unknown error connecting to the Livebox: Unexpected response, content-type incorrect text/html
Unknown error connecting to the Livebox: Open session failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiosysbus/aiosysbus.py", line 74, in async_connect
    await self._auth.async_get_session_token()
  File "/usr/local/lib/python3.11/site-packages/aiosysbus/auth.py", line 206, in async_get_session_token
    raise UnexpectedResponse(
aiosysbus.exceptions.UnexpectedResponse: Unexpected response, content-type incorrect text/html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/livebox/config_flow.py", line 90, in async_step_user
    await api.async_connect()
  File "/usr/local/lib/python3.11/site-packages/aiosysbus/aiosysbus.py", line 78, in async_connect
    raise AiosysbusException(error) from error
aiosysbus.exceptions.AiosysbusException: Unexpected response, content-type incorrect text/html

**Comment by cyr-ius** [comment]
Sorry but I don't know this model. Unable to identify the livebox6+, is it a professional livebox?
The Pro model is not compatible with the addon
The error return indicates that the API does not produce JSON

**Comment by dusnake** [comment]
1.1.  fabricante.   ARLT
1.2.  modelo.   ARLTLBPLU6
1.3.   operadorNEBA    (Orange)
1.4.  número de serie.     ARLT234C6384

**Comment by ddeekuu** [comment]
same happening here with livebox 6, ig it is because what dusnake and I are using is the Spain's version of the livebox xD

**Comment by reddorf** [comment]
Same here using

Maker: Arcadyan
Model: PRV3399B_B_LT
Middleware version: AR_LBFIBRA_sp-00.03.05.227C
Hardware version: ARLTLBFIB2.0.0

It's [this](https://openwrt.org/inbox/toh/arcadyan/astoria/prv3399b-e-lt) router.
