### ISSUE TITLE
Issue with Core 2024.1

### ISSUE THREAD

**Issue by TeddyLafrite** [cyr-ius/hass-livebox-component#88]
Logger: homeassistant.const
Source: helpers/deprecation.py:204
First occurred: 23:15:12 (1 occurrences)
Last logged: 23:15:12

DATA_RATE_MEGABITS_PER_SECOND was used from livebox, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfDataRate.MEGABITS_PER_SECOND instead, please create a bug report at https://github.com/cyr-ius/hass-livebox-component/issues

-----

Logger: homeassistant.components.sensor
Source: helpers/deprecation.py:204
Integration: Capteur (documentation, issues)
First occurred: 23:15:12 (2 occurrences)
Last logged: 23:15:12

STATE_CLASS_MEASUREMENT was used from livebox, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.MEASUREMENT instead, please create a bug report at https://github.com/cyr-ius/hass-livebox-component/issues

-----

Logger: homeassistant.components.device_tracker
Source: helpers/deprecation.py:204
Integration: Dispositif de suivi (documentation, issues)
First occurred: 23:15:18 (2 occurrences)
Last logged: 23:15:19

SOURCE_TYPE_ROUTER was used from livebox, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.ROUTER instead, please create a bug report at https://github.com/cyr-ius/hass-livebox-component/issues

**Comment by cyr-ius** [comment]
Please test this version 1.8.9-beta1
In HACS , select 3points , Redownload , Beta enable and select version

**Comment by TeddyLafrite** [comment]
Hi @cyr-ius 

It's OK with 1.8.9-beta1

Thanks
