### ISSUE TITLE
[How-To] remove devices trackee

### ISSUE THREAD

**Issue by Matssa56** [cyr-ius/hass-livebox-component#92]
Hi!

First off thanks for this 🙂

Is there a way to remove the tracked devices under the integration? I don't want to link my Livebox to other entities / devices (I have a second router).

![Screenshot_20240114-004445](https://github.com/cyr-ius/hass-livebox-component/assets/16662808/b405adce-5d2e-4cdc-9d05-7202acbee423)

Thanks!

**Comment by LGO44** [comment]
``
First , you have to clean the history of connected devices in the live box
Second, you have to suppress the livebox in the integration and to recreate it.

The tracked devices are not suppressed as they are not connected, this is the aim of that: track the devices connected once to the livebox...

**Comment by Matssa56** [comment]
> `` First , you have to clean the history of connected devices in the live box Second, you have to suppress the livebox in the integration and to recreate it.
> 
> The tracked devices are not suppressed as they are not connected, this is the aim of that: track the devices connected once to the livebox...

Hi,

Thanks for your help, I didn't know there was a history in Livebox.

Mersi bras et kenavo! ;)
